### ISSUE TITLE
How to change the pulse color ?

### ISSUE THREAD

**Issue by Yohandah** [willmendesneto/ngx-skeleton-loader#111]
**I'm submitting a ...** (check one with "x")

- [ ] bug report => search github for a similar issue or PR before submitting
- [x ] feature request

**Current behavior**

If I'm setting a white background 
```
[theme]="{
            'border-radius': '5px',
            height: '50px',
            'background-color': 'white',
            border: '1px solid #b3c0cb'
          }"
```
The pulse cannot be seen, I would like to change its color but can we ? It's setted right there but can we access it with [theme] ?

![image](https://user-images.githubusercontent.com/15921402/171381125-46a8e827-af11-408e-8af5-1be18608c87a.png)

**Comment by willmendesneto** [comment]
Hi @Yohandah ! Thanks for raising this issue.

At the moment, the way to change the color is by changing via Stylesheet file, not via `theme`. Here's a live example of changing the pulse and progress colors, respectively.

https://stackblitz.com/edit/ngx-skeleton-loader-user-card-component-sample-tmnupm?file=src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.component.css,src%2Fapp%2Fapp.component.html

**Comment by willmendesneto** [comment]
Closing this issue for now. Once again, thanks for raising that, @Yohandah !
