### ISSUE TITLE
Support angular 14

### ISSUE THREAD

**Issue by trentprynn** [willmendesneto/ngx-skeleton-loader#113]
**I'm submitting a ...**

- [ ] bug report => search github for a similar issue or PR before submitting
- [x] feature request

**Current behavior**

only angular@13 is supported

**Expected behavior**

angular@14 is supported

**Comment by BruneXX** [comment]
Please add support for angular v14.x

**Comment by CodeWorldIndustries** [comment]
@BruneXX @trentprynn for now you can just provide a theme. E.g.:   NgxSkeletonLoaderModule.forRoot({ theme: { 'background-color': '#ff0000', opacity: '0.9' } })

Looks like v14 of Angular isn't picking it up by default

**Comment by trentprynn** [comment]
Sorry, I think I misunderstood the library setup when I opened this issue. I checked the package.json in the root of this project and saw angular@13 dependencies but now realize that’s just for testing+development of the actual library. I am not using this on an angular14 project yet so I cannot confirm experience but feel free to close if angular14 is supported 👍🏼

**Comment by willmendesneto** [comment]
All good, @trentprynn , nothing to worry about! Thanks for clarifying your point!

I'm closing this issue for now, but please feel free to reopen if you feel it's an issue!
