### ISSUE TITLE
Please improve documentation

### ISSUE THREAD

**Issue by saadmomin** [willmendesneto/ngx-skeleton-loader#14]
**I'm submitting a ...** (check one with "x")

```
[ ] bug report => search github for a similar issue or PR before submitting
[x ] feature request
```

**Current behavior**

How do i create a theme and change styling?

**Expected behavior**

**Reproduction of the problem**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

- **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX |
  Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

  

- **Language:** [all | TypeScript X.X | ES6/7 | ES5]

- **Node (if applicable):** `node --version` =

**Comment by willmendesneto** [comment]
Hi @saadmomin , thanks for raising the issue. 

There's an example on the Stackblitz Demo in the package README.md

https://stackblitz.com/edit/ngx-skeleton-loader-sample

As an example, this is the code you can find in the stackblitz link

```html
<ngx-skeleton-loader
    count="5"
    [theme]="{ 
      'border-radius': '5px',
      height: '50px',
      'background-color': '#992929',
      border: '1px solid white'
    }"
  ></ngx-skeleton-loader>
```

This will generate a theme with the given theme.

<img width="502" alt="Screen Shot 2019-12-18 at 7 00 27 pm" src="https://user-images.githubusercontent.com/1252570/71067476-b27e0300-21c8-11ea-9650-05c19c207399.png">


I'll update the docs adding this on the README.md directly to make it easier to find.

**Comment by willmendesneto** [comment]
I just added the section with the details for theming on the `README.md` in this commit https://github.com/willmendesneto/ngx-skeleton-loader/commit/071b723a319df1a7954d165f10c23ce272efee64

I'm closing this issue for now. Thanks @saadmomin !

**Comment by lartheon** [comment]
"After that, you can use the ngx-skeleton-loader components in your templates, passing the configuration data into the component itself."

hi, it would be really great if you could provide an example of how this integrates into a working application, eg if I have a bio page with image and textboxes etc.
PS I'm a newbie to Angular

**Comment by willmendesneto** [comment]
Hi @lartheon . Welcome aboard! Nothing to worry about, mate. We're all newbies ^^

Could you elaborate more about it, please? You're talking about have the Stackblitz examples improved or create a sample application sharing the module integration?

This repository is using Stackblitz demo to show how to integrate the module, so I think we can do some sparring on your idea without any geographic friction. 

Stackblitz link: https://stackblitz.com/edit/ngx-skeleton-loader-sample

If you can share more details about your idea will be amazing! I'm keen to improve the docs :)

**Comment by lartheon** [comment]
Hi, thank you for taking time to respond. My impression of a skeleton UI was that it could be used as a placeholder whilst the application processed a command e.g a GET request. Once the request had been processed the UI would change according to the response (hopefully revealing the content requested by the client).  

Hope that makes sense.
