### ISSUE TITLE
Possible Angular Universal memory leak

### ISSUE THREAD

**Issue by screeny05** [willmendesneto/ngx-skeleton-loader#144]
**I'm submitting a ...** (check one with "x")

- [x] bug report => search github for a similar issue or PR before submitting ✅ 
- [ ] feature request

**Current behavior**

This package creates `PerformanceMeasure` objects, using the perf-marks library. These objects stay in the memory, due to them not being cleared after a ssr-request. So every ssr-rendered request leaves behind a few `PerformanceMeasure` objects for each rendered NgxSkeletonLoader. After a while, this can become quite a lot if the angular-universal-server is not restarted frequently.

![grafik](https://user-images.githubusercontent.com/765896/231470887-a417c95e-d0ce-4de6-897a-dd4da6badc1a.png)

You can see here, that this heap-snapshot of our production-application contains ~676664 `PerformanceMeasure`-objects. With each weighing in at 64 byte. This may not seem like much, but for a production-application this is not tolerable.

I think this is an unintentional memory-leak that should be fixed.

**Expected behavior**

Possible solutions:
1. Let the developer disable these performance-measures
2. Do not ship them in production-builds
3. Clear them after every request, or
4. Make it clear in the documentation that using this library will lead to memory-leaks in ssr when not handled manually

**Reproduction of the problem**

1. Create a new angular-application with angular universal
2. Add a whole bunch of ngx-skeleton elements to the page
3. Run a load-test
4. Take a heap-snapshot

For our production-environment i've worked around this issue by calling `PerfMarks.clearAll()` and `performance.clearMeasures()` after every ssr-response.

**What is the motivation / use case for changing the behavior?**

Removing a possible memory-leak

**Please tell us about your environment:**

```
"ngx-skeleton-loader": "2.9.1",
"@angular/core": "15.1.1",
"@nguniversal/common": "15.1.0",
"@nguniversal/express-engine": "15.1.0",
"express": "4.18.2",
```

Node v18.15.0
Ubuntu 20.04.6
Nginx as reverse-proxy

- **Browser:** all

  

- **Language:** all

- **Node (if applicable):** `node --version` = 18.15.0

**Comment by willmendesneto** [comment]
Hi @screeny05 thanks for raising this issue and for adding these steps. They're quite handy!

Have you tried to upgrade the package to the latest version? I've seen this issue getting fixed by doing that and since you're on the latest versions of Angular, I believe you won't face anything massive such as breaking changes and such. Maybe this will fix the issue without further implementation requirement.

> For our production-environment i've worked around this issue by calling PerfMarks.clearAll() and performance.clearMeasures() after every ssr-response.

Could you add more information about this step in specific, please?

Once again, thanks heaps!

**Comment by screeny05** [comment]
I will try that later. Can't believe i did not think about checking the version.

> Could you add more information about this step in specific, please?

Sure! Our SSR-process basically looks like this:

```
import * as PerfMarks from 'perf-marks/marks';

const garbageCollectSSR = () => {
  PerfMarks.clearAll();
  performance.clearMeasures.();
};

const server = express();
server.engine('html', ngExpressEngine({ bootstrap: AppServerModule }));

server.get('*', (req, res) => {
  res.render('dist/browser/index.html', { req }, (_, html) => {
    garbageCollectSSR();
    res.send(html)
  })
});
```

**Comment by screeny05** [comment]
Hey @willmendesneto,

unfortunately i'm still able to reproduct this issue on version 7.0.0.

<img width="622" alt="grafik" src="https://user-images.githubusercontent.com/765896/232030799-b56603b3-713b-45f0-8853-79fc0660382e.png">

**Comment by ArxPasmahe** [comment]
+1, what is the benefit of having this perf-marks lib in production builds?

**Comment by willmendesneto** [comment]
Hey folks.  Sharing some good news with y'all! I just added this commit here which is fixing this issues by removing `perf-marks` https://github.com/willmendesneto/ngx-skeleton-loader/commit/988e53845cd8c5239c90af20676d21d1404924e1

Thanks for raising and keep tracking this issue!

**Comment by willmendesneto** [comment]
Happy to share this fix is now available on the latest version of `ngx-skeleton-loader`

Please, update your project dependencies to use the version `ngx-skeleton-loader@8.0.0`
