### ISSUE TITLE
Unable run in Angular 11

### ISSUE THREAD

**Issue by sylvester-x** [willmendesneto/ngx-skeleton-loader#151]
**I'm submitting a ...** (check one with "x")

- [x ] bug report => search github for a similar issue or PR before submitting
- [ ] feature request

**Current behavior**
currently i installed ngx-skeleton-loader:7.0.0
when ng serve, it show error

Error: ./node_modules/ngx-skeleton-loader/fesm2015/ngx-skeleton-loader.mjs 172:6-19
Can't import the named export 'ɵɵtemplate' from non EcmaScript module (only default export is available)

![image](https://github.com/willmendesneto/ngx-skeleton-loader/assets/45072247/eddca8ef-d9ae-48ba-9da8-e98fdd59d7ca)

![image](https://github.com/willmendesneto/ngx-skeleton-loader/assets/45072247/1e25cd41-2962-4ec4-9fb0-feb55b81db3b)

**Comment by willmendesneto** [comment]
Hi @sylvester-x , thanks for raising this issue!

It seems this comment solves your issue. Unfortunately, you might need to downgrade the package usage to consume `ngx-skeleton-loader@v6.0.0`

More details in this link: https://github.com/willmendesneto/ngx-skeleton-loader/issues/150#issuecomment-1638612329

Closing this issue for now! Once again, thanks for raising that!

**Comment by willmendesneto** [comment]
Hi 👋 

just sharing some great news! This code was replaced and you can now upgrade your project to use `ngx-skeleton-loader@8.1.0` to get the latest fixes and improvements so far!
