### ISSUE TITLE
Version 8 is not published in Releases

### ISSUE THREAD

**Issue by MattAllison** [willmendesneto/ngx-skeleton-loader#153]
**I'm submitting a ...** (check one with "x")

- [ ] bug report => search github for a similar issue or PR before submitting
- [ x] feature request

**Current behavior**

The current release doesn't show as a Release - it is only tagged.

**Comment by willmendesneto** [comment]
Hi, @MattAllison , thanks for raising this issue.

The current release is tagged and published. Sharing here some links confirming that:
- NPM Release: https://www.npmjs.com/package/ngx-skeleton-loader/v/8.0.0
- Stackblitz example pointing to `ngx-skeleton-loader@8.0.0`: https://stackblitz.com/edit/ngx-skeleton-loader-sample?file=src%2Fapp%2Fapp.component.ts
- Tag and sources: https://github.com/willmendesneto/ngx-skeleton-loader/releases/tag/v8.0.0

I'm closing this issue for now. Once again, thanks for raising that, @MattAllison !
