### ISSUE TITLE
Meta data version mismatch for module found version 4, expected 3.

### ISSUE THREAD

**Issue by rafayck** [willmendesneto/ngx-skeleton-loader#16]
**I'm submitting a ...** (check one with "x")

```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
```

I'm trying to build my angular app with "gulp clean && gulp build:universal-prod --env prod" using ngx-skeleton-loader. 

The library appears to work fine but gives me an error while creating the build. 

Error: Error: Metadata version mismatch for module /home/rafay/Desktop/Project-Web/node_modules/ngx-skeleton-loader/ngx-skeleton-loader.d.ts, found version 4, expected 3
    at StaticSymbolResolver.getModuleMetadata (/home/rafay/Desktop/Project-Web/node_modules/@angular/compiler/@angular/compiler.es5.js:24469:7)
    at StaticSymbolResolver._createSymbolsOf (/home/rafay/Desktop/Project-Web/node_modules/@angular/compiler/@angular/compiler.es5.js:24255:46)

Reproduce:
build project with ng build --prod

Requesting support for angular 4. There must be an angular 4 compatible version for ngx-skeleton-loader

Using the following versions for angular:

    "@angular/animations": "4.1.0",
    "@angular/cdk": "2.0.0-beta.8",
    "@angular/common": "~4.1.0",
    "@angular/core": "~4.1.0",
    "@angular/forms": "~4.1.0",
    "@angular/http": "~4.1.0",
    "@angular/material": "2.0.0-beta.8",
    "@angular/platform-browser": "~4.1.0",
    "@angular/platform-browser-dynamic": "~4.1.0",
    "@angular/platform-server": "~4.1.0",
    "@angular/router": "~4.1.0"

- **Language:** [ TypeScript 3.6.3 | ES6 ]

- `node --version` = 8.16.2 
- npm -v = 6.4.1

**Comment by willmendesneto** [comment]
Hi @rafayck , thanks for open this issue. 

Could you share more information about this issue, please? It would be amazing if we could have a similar environment as the one you're facing the issue, so we can make sure it's related to the module and that can be fixed as quickly as possible.

**Comment by rafayck** [comment]
@willmendesneto thankyou for responding

Im sharing my devDependencies and dependencies first,
"devDependencies": {
    "@angular/cli": "^7.3.9",
    "@angular/compiler": "~4.1.0",
    "@angular/compiler-cli": "~4.1.0",
    "@ngtools/webpack": "^1.3.1",
    "@types/core-js": "^0.9.41",
    "@types/express": "^4.17.1",
    "@types/jasmine": "^2.5.47",
    "@types/lodash": "^4.14.138",
    "@types/node": "^7.10.7",
...
}
dependencies : {
"@angular/animations": "4.1.0",
    "@angular/cdk": "2.0.0-beta.8",
    "@angular/common": "~4.1.0",
    "@angular/core": "~4.1.0",
    "@angular/forms": "~4.1.0",
    "@angular/http": "~4.1.0",
    "@angular/material": "2.0.0-beta.8",
    "@angular/platform-browser": "~4.1.0",
    "@angular/platform-browser-dynamic": "~4.1.0",
    "@angular/platform-server": "~4.1.0",
    "@angular/router": "~4.1.0",
    "@angularclass/bootloader": "^1.0.1",
    "@ng-bootstrap/ng-bootstrap": "^1.0.0-alpha.26",
    "@nguniversal/express-engine": "^1.0.0-beta.2",
    "@ngx-cache/core": "~0.4.0-beta.1",
    "@ngx-cache/fs-storage": "~0.4.0-beta.2",
    "@ngx-cache/platform-browser": "~0.4.0-beta.1",
    "@ngx-cache/platform-server": "~0.4.0-beta.1",
    "@ngx-config/core": "~0.2.0-rc.5",
    "@ngx-config/fs-loader": "~0.2.0-beta.1",
    "@ngx-config/http-loader": "~0.2.0-rc.1",
    "@ngx-i18n-router/config-loader": "~0.2.0-rc.3",
    "@ngx-i18n-router/core": "~0.4.0-beta.2",
    "@ngx-meta/core": "~0.4.0-rc.2",
    "@ngx-translate/core": "^6.0.1",
    "@ngx-translate/http-loader": "~0.0.3",
    "@ngx-universal/config-loader": "~0.4.0-rc.1",
    "@ngx-universal/state-transfer": "~0.4.0-beta.1",
    "@ngx-universal/translate-loader": "~0.4.0-beta.1",
    "@trademe/ng-defer-load": "^3.1.0",
...
}

the error occurs when I build my app with **gulp clean && gulp build:universal-prod --env prod**

I am assuming it has more to do with version incompatibility. However, the skeleton loader works fine, just doesn't build.

**Comment by willmendesneto** [comment]
just checking again with you. Is there any specific reason to mix angular CLI and Gulp on it?

**Comment by willmendesneto** [comment]
Hey @rafayck 

I took a look at these packages and also tried to simulate that, but with no success. What I could find is that it can be happening due to the versions of `@angular` packages and `ngx-skeleton-loader` requiring an angular version above that.

In that case, your option is to upgrade your angular dependencies to use something above the latest (ideal) or at least >= v7. Unfortunately, the first package of this package is using v7 for all `@angular` packages, so add support for it won't be possible in that case.

**Comment by willmendesneto** [comment]
Closing this issue for now due to lack of response. Thanks @rafayck !
