### ISSUE TITLE
demo no workey?

### ISSUE THREAD

**Issue by sommmen** [willmendesneto/ngx-skeleton-loader#166]
https://ngx-skeleton-loader-sample.stackblitz.io/

![image](https://github.com/willmendesneto/ngx-skeleton-loader/assets/8641495/cbc8862f-ab99-4645-bc48-55a78c14fd82)

**Comment by willmendesneto** [comment]
Thanks for raising this issue, @sommmen 

The is fixed now! Closing this issue for the greater good!
