### ISSUE TITLE
Peer dependency warnings with Angular 9

### ISSUE THREAD

**Issue by abraham** [willmendesneto/ngx-skeleton-loader#17]
**I'm submitting a ...** (check one with "x")

```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
```

**Current behavior**

Throws peer dependency warnings running `npm install` when used with Angular 9.

> npm WARN ngx-skeleton-loader@1.2.2 requires a peer of @angular/common@^8.0.0 but none is installed. You must install peer dependencies yourself.
> npm WARN ngx-skeleton-loader@1.2.2 requires a peer of @angular/core@^8.0.0 but none is installed. You must install peer dependencies yourself.

**Expected behavior**

Not to have warnings when running `npm install`

**Reproduction of the problem**

Install in an Angular 9 app.

**What is the motivation / use case for changing the behavior?**

Angular 9 went stable recently and it would be great to use this without warnings.

**Comment by willmendesneto** [comment]
Hi @abraham ! Thanks for raising this issue.

I'll be looking at it in the next days and I'll add this version on the upgraded version of this package.

**Comment by willmendesneto** [comment]
Hey @abraham . I just published a new version of this package with the fix. I applied a fix, and tested with no issues so far.

Could you upgrade your project to the latest version `ngx-skeleton-loader@1.2.3` and reply to this issue, please? I just want to confirm that's solving your issue, so I can close it.

**Comment by abraham** [comment]
Looks good! Thanks
