### ISSUE TITLE
Implement feature to allow flexbox styling

### ISSUE THREAD

**Issue by shinkhouse** [willmendesneto/ngx-skeleton-loader#22]
**I'm submitting a ...** (check one with "x")

- [ ] bug report => search github for a similar issue or PR before submitting
- [ x] feature request

**Current behavior**

I'm experiencing an issue when I attempt to use display: flex with ngx-skeleton-loader. 

**Expected behavior**

Given a count of 8 loaders, display loaders using display: flex and flex-direction-row. 

**Reproduction of the problem**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

macOS Catalina 15.4.0

- **Browser:** [Chrome 80.0.3987.163 ]

  

- **Language:** [all | TypeScript X.X | ES6/7 | ES5]
```
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 9.1.1
Node: 13.11.0
OS: darwin x64

Angular: 9.1.2
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.1
@angular-devkit/build-angular     0.901.1
@angular-devkit/build-optimizer   0.901.1
@angular-devkit/build-webpack     0.901.1
@angular-devkit/core              9.1.1
@angular-devkit/schematics        9.1.1
@angular/cdk                      9.2.1
@angular/cli                      9.1.1
@angular/flex-layout              9.0.0-beta.29
@angular/material                 9.2.1
@ngtools/webpack                  9.1.1
@schematics/angular               9.1.1
@schematics/update                0.901.1
ngx-skeleton-loader 1.2.7
rxjs                              6.5.5
typescript                        3.7.5
webpack                           4.42.0

```

- **Node (if applicable):** `node --version` = 13.11.0

**Comment by willmendesneto** [comment]
Hey @shinkhouse , thanks for raising this issue.

Could you clarify some points about this issue, please? It would be amazing if you could also give me some real example by forking the Stackblitz example using `ngx-skeleton-loader` https://stackblitz.com/edit/ngx-skeleton-loader-sample

Happy to apply the changes or give some guidance on it, just asking for more information about your scenario. So that we can have the fix applied ASAP.

**Comment by shinkhouse** [comment]
Hey @willmendesneto, thanks for the reply. I will fork this project and get back to you later today. Thanks for your help!

**Comment by willmendesneto** [comment]
Hey @shinkhouse 

Any success on this one? I'll try to play with that in the next days in case you weren't able to check. In the meantime, if you can share as much information as you have about it I really appreciate. That can make the release for the fix even faster!

**Comment by willmendesneto** [comment]
Hey @shinkhouse 

I'm closing this issue due to the delay in our conversation. But please, feel free to reopen it anytime, so we can check that out.

Thanks for that!
