### ISSUE TITLE
Using theme attribute with css class ?

### ISSUE THREAD

**Issue by carlabruti** [willmendesneto/ngx-skeleton-loader#25]
**I'm submitting a ...** (check one with "x")

- [ ] bug report => search github for a similar issue or PR before submitting
- [x] feature request

**Current behavior**

i have to put all of my theme in html view when using ngx-skeleton-loader

**Expected behavior**

i would like to pass a css class to the theme attribute in html view when using ngx-skeleton-loader

**Reproduction of the problem**

<ngx-skeleton-loader
    count="5"
    animation="pulse"
    [theme]="my-css-class">
  </ngx-skeleton-loader>

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

- **Browser:** [Chrome XX | Firefox XX]

- **Language:** [TypeScript 3.8 | ES5]

- **Node (if applicable):** `node --version` =

**Comment by willmendesneto** [comment]
Hi, @carlabruti thanks for raising this issue. Could you elaborate more on the feature itself?

Just trying to understand the scenario that can be useful and that disabling the animation and add your class directly into the component is not covering.

```html
  <ngx-skeleton-loader
    count="5"
    animation="false"
    appearance="circle"
  ></ngx-skeleton-loader>
```

> For more details about it, please check the Section "Skeletons without animation" in Stackblitz demo: https://stackblitz.com/edit/ngx-skeleton-loader-sample?file=app%2Fapp.component.html

Could you share some examples with some scenarios of this request, please?

**Comment by carlabruti** [comment]
hi,
sorry for late response,

I would like to avoid putting style in my html view. And in case i need to duplicate skeleton in an other view i will need to duplicate also theme style.

Here is actual code :

`<ngx-skeleton-loader
    count="5"
    animation="pulse"
    [theme]="{
      'border-radius': '0.3rem',
      height: '4rem',
      border: '0.06rem solid white'}">
  </ngx-skeleton-loader>`

Here is what i would like to be able to do :

`<ngx-skeleton-loader
    count="5"
    animation="pulse"
    [theme]="skeleton-css-class">
  </ngx-skeleton-loader>

.skeleton-css-class {
      'border-radius': '0.3rem',
      height: '4rem',
      border: '0.06rem solid white'}`

I tried something like this in my css file, but i was not able to make i worked (i may have did something wrong) : 
`  ngx-skeleton-loader {
    span {
      border-radius: 0.3rem;
      height: 4rem;
      border: 0.06rem solid white;
    }
  }`

Sorry for aproximative english (not my native language) :(

**Comment by willmendesneto** [comment]
I see what are you trying to do. In that case, you can do something using `::host >>>` to specify that.E.G.

Based on your example, your HTML code will be

```html
<ngx-skeleton-loader
    count="5"
    animation="pulse"
  ></ngx-skeleton-loader>
```

And your stylesheet will be
```css
:host >>> ngx-skeleton-loader .loader {
  border-radius: 0.3rem !important;
  height: 4rem;
  border: 0.06rem solid white;
}
```
or you can check this live example at Stackblitz

https://stackblitz.com/edit/ngx-skeleton-loader-sample-using-styles-instead-of-theme?file=app/app.component.css

PS: Don't worry about the english, it's not my first language as well (I'm originally from Brazil). Express yourself in a different language is something amazing and I have to say you're doing such a greaj job <3 ! Keep rocking!

**Comment by willmendesneto** [comment]
Also, I added this approach on the docs in this commit https://github.com/willmendesneto/ngx-skeleton-loader/commit/a2a7abd29412beca430e7b0caaa744b5a89db793 . I'm closing this issue for now, but feel free to open it if necessary!

One more time, thanks for raising this issue!
