### ISSUE TITLE
ie11上面报错 ERROR TypeError: 对象不支持“includes”属性或方法

### ISSUE THREAD

**Issue by yinuocode** [willmendesneto/ngx-skeleton-loader#26]
<ngx-skeleton-loader count="3" animation="progress"></ngx-skeleton-loader>

ie11上面报错 ERROR TypeError: 对象不支持“includes”属性或方法

**Comment by willmendesneto** [comment]
Sharing here for transparency in share the solution. 

One more time, thanks @yinuocode for raising this pull request! https://github.com/willmendesneto/ngx-skeleton-loader/pull/27

**Comment by willmendesneto** [comment]
I just published a new version with the fix 🎉 , so I'm closing this issue for now.

Please upgrade your project to use `ngx-skeleton-loader@2.2.1` and, one more time, thanks for raising the fix @yinuocode !

**Comment by yinuocode** [comment]
npm上没有`2.2.1` 的版本，安装不了`2.2.1`的版本
yarn add ngx-skeleton-loader@2.2.1
yarn add v1.22.4
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] 🔍  Resolving packages...
Couldn't find any versions for "ngx-skeleton-loader" that matches "2.2.1"
? Please choose a version of "ngx-skeleton-loader" from this list: 
❯ 2.2.0 
  2.1.0 
  2.0.0 
  1.2.7 
  1.2.6 
  1.2.3 
  1.2.2 
  1.2.1 
  1.2.0 
  1.1.2 
  1.1.1 
  1.1.0 
  1.0.2 
  1.0.0

**Comment by willmendesneto** [comment]
You mistyped the package version when you were running `yarn add`. It should be `yarn add ngx-skeleton-loader@2.2.1`.

You can also check the version here at Stackblitz https://stackblitz.com/edit/ngx-skeleton-loader-sample

Could you confirm if that's working for you, please?

<img width="1674" alt="Screen Shot 2020-07-03 at 2 03 55 am" src="https://user-images.githubusercontent.com/1252570/86433666-bb03da00-bcd1-11ea-90fc-ed16c668d556.png">

**Comment by yinuocode** [comment]
Thank you for your reply, but I really cannot install 2.2.1 on my computer, as shown in the figure below

<img width="594" alt="WX20200703-133504@2x" src="https://user-images.githubusercontent.com/8911142/86435245-21b8e000-bd32-11ea-8ac6-34e5349fc889.png">

**Comment by willmendesneto** [comment]
Interesting ... I tried that locally and it works as expected. Also, it's working on stackblitz, which downloads the packages via NPM/YARN.

<img width="1460" alt="Screen Shot 2020-07-03 at 2 23 20 pm" src="https://user-images.githubusercontent.com/1252570/86488934-04d3db00-bd39-11ea-84d6-dfecdeefd159.png">

I'm pretty sure that's something related to your local configuration and/or internet connection. Could you check if you are not having any issue with local proxy or the package managers trying to download from local first? What I can suggest:

- Try to remove the NPM/YARN local cache
- Check your NPM/YARN registry configuration
- Check if your package managers are trying to prioritize cached packages. If that's the case, use it forcing to download the packages
- Not sure if you're using a private project with a private npm. If that's the case, please check the configuration for it to see if does the fallback to check NPM/YARN registry to make sure it's doing in case there's no cached package

**Comment by willmendesneto** [comment]
I'm closing this issue for now since I didn't get any reply, so I'm assuming that was the issue and it's solved.

Thanks @yinuocode ! 🎉
