### ISSUE TITLE
'ngx-skeleton-loader' is not a known element:

### ISSUE THREAD

**Issue by tranvannhat** [willmendesneto/ngx-skeleton-loader#3]
I follow doc, but get error: 'ngx-skeleton-loader' is not a known element:....

**Comment by willmendesneto** [comment]
Hi @tranvannhat . Could you share more information about the  issue, please?

Have you tried the Demo example? 

https://stackblitz.com/edit/ngx-skeleton-loader-sample?file=app%2Fapp.component.html

**Comment by willmendesneto** [comment]
Closing this issue due to the lack in reply. Thanks @tranvannhat , feel free to reopen it if needed

**Comment by rubenheymans** [comment]
you should add ```import { NgxSkeletonLoaderModule } from 'ngx-skeleton-loader';``` to the docs, it's not clear

**Comment by haucongle** [comment]
I got the same problem
// app.module..ts
`import { NgxSkeletonLoaderModule } from 'ngx-skeleton-loader';`
```
imports: [
    NgxSkeletonLoaderModule,
    ...
  ],
```
// app.component.html
`<div class="item"><ngx-skeleton-loader count="5" appearance="circle"> </ngx-skeleton-loader></div>
`

And here is the error
```
ERROR in 'ngx-skeleton-loader' is not a known element:
1. If 'ngx-skeleton-loader' is an Angular component, then verify that it is part of this module.
2. If 'ngx-skeleton-loader' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("<div class="item">[ERROR ->]<ngx-skeleton-loader count="5" appearance="circle"> </ngx-skeleton-loader></div>
")
```

**Comment by willmendesneto** [comment]
@haucongle Looks like you're missing something in your local configuration. Could you check the stackblitz example (https://stackblitz.com/edit/ngx-skeleton-loader-sample?file=app%2Fapp.module.ts), please?

The previous issue was solved by adding this step in the docs. If this issue still persists, could you please share a stackblitz link simulating your issue?

**Comment by haucongle** [comment]
@willmendesneto I think I know my problem now because I put tag `ngx-skeleton-loader` in a component (not app component) whose its module did not import `NgxSkeletonLoaderModule`.  So I have to import ``NgxSkeletonLoaderModule`` in many modules manually. Could you support import module for root like this `NgxSkeletonLoaderModule.forRoot()`. Thanks

**Comment by willmendesneto** [comment]
Sure thing. What I can suggest for now is to add it in the correct module until we have a `forRoot` in the module

**Comment by LeentechDev** [comment]
does it still not support for root ??

**Comment by willmendesneto** [comment]
@LeentechDev Unfortunately, I didn't have proper time to look at it. I'll try to apply that in the next weeks. This can be a great opportunity for pull requests. 

Until we have the support in place, I strongly suggest you to use https://github.com/willmendesneto/ngx-skeleton-loader/issues/3#issuecomment-542433960 as a solution.

**Comment by Sayrai** [comment]
@willmendesneto I'm still getting the following error :

'ngx-skeleton-loader' is not a known element:
1. If 'ngx-skeleton-loader' is an Angular component, then verify that it is part of this module.
2. If 'ngx-skeleton-loader' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.ng

after importing  NgxSkeletonLoaderModule from 'ngx-skeleton-loader' in my app.module.ts and also the parent module of the component.

**Comment by willmendesneto** [comment]
Hi @Sayrai. Could you share more information about the issue, please?

If possible, could you fork and create an example based on the Stackblitz demo? At first, moment, looks like a issue with module configuration really, but it's good to get more details about it. So that I can help your scenario.

https://stackblitz.com/edit/ngx-skeleton-loader-sample?file=app%2Fapp.component.html

**Comment by willmendesneto** [comment]
Also, I'm happy to share there's a new `NgxSkeletonLoaderModule.forRoot()` method available. More details in this pull request https://github.com/willmendesneto/ngx-skeleton-loader/pull/48

**Comment by willmendesneto** [comment]
In addition of that, I just updated the examples to use the new `.forRoot()` method as well. You can find a live example in https://stackblitz.com/edit/ngx-skeleton-loader-user-card-component-sample?file=app%2Fapp.module.ts

**Comment by silnose** [comment]
same issue :( 

``` 
error NG8001: 'ngx-skeleton-loader' is not a known element:
1. If 'ngx-skeleton-loader' is an Angular component, then verify that it is part of this module.
2. If 'ngx-skeleton-loader' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.

11     <ngx-skeleton-loader *ngIf="isImageLoading"> </ngx-skeleton-loader>
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  src/app/modules/location-manager/components/media-manager/components/add-media-button/add-media-button.component.ts:11:16
    11   templateUrl: './add-media-button.component.html',
                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component AddMediaButtonComponent.

``` 

app.module.ts

```
import { NgxSkeletonLoaderModule } from 'ngx-skeleton-loader';


(...)

import: [ NgxSkeletonLoaderModule.forRoot() ]
```

**Comment by jelitter** [comment]
Any solution for this ? I'm facing the same issue, both importing NgxSkeletonLoaderModule in the main module (app.module.ts) and in my component's module, both with 'forRoot' and without.

Angular 11.0.2
ngx-skeleton-loader: "^4.0.0"

Thanks!

**Comment by willmendesneto** [comment]
@jelitter , @silnose  

This is an old issue related to a misconfiguration, as mentioned in this comment here https://github.com/willmendesneto/ngx-skeleton-loader/issues/3#issuecomment-727525941 .  In any case, I'm more than happy to help, but it would be great if I can have a real scenario simulation. Could you folks fork this Stackblitz example, simulate the issue, and share the link here, please?

https://stackblitz.com/edit/ngx-skeleton-loader-user-card-component-sample

**Comment by johnMyjourney** [comment]
Hi there, I use Angular 9.1.3.
Same issues when I try to used this components. 

I try to follow the guild and import the Module like this.
`import: [ NgxSkeletonLoaderModule.forRoot() ]`

but it still show this error

`class NgxSkeletonLoader Module is not a angular module`

**Comment by willmendesneto** [comment]
Hi @johnMyjourney . The issue you're facing is related to some misconfiguration in your application. To solve that, please follow these steps and check the Stackblitz example as linked in this comment https://github.com/willmendesneto/ngx-skeleton-loader/issues/3#issuecomment-998259108

In case you feel is not related to that, could you please provide a Stackblitz link that simulates your issue and share it, please?

Cheers!

**Comment by lukyncze** [comment]
Hi I am facing the same issue as e.g. https://github.com/willmendesneto/ngx-skeleton-loader/issues/3#issuecomment-542117812.

I tried to check both code examples, but either of them doesn´t work for me - they literally said "Starting dev server" for a long time :/
https://stackblitz.com/edit/ngx-skeleton-loader-sample?file=app%2Fapp.module.ts
https://stackblitz.com/edit/ngx-skeleton-loader-user-card-component-sample?file=app%2Fapp.module.ts

On the other hand, I think I did setup ngx-skeleton-loader as it docs says (and also same way as docs): https://www.npmjs.com/package/ngx-skeleton-loader#setup

I am using:
"@angular/core": "^13.2.6",
"ngx-skeleton-loader": "^6.0.0",

What should I try, please?

Thanks in advance!
