### ISSUE TITLE
How to change color bar skeleton

### ISSUE THREAD

**Issue by raihan71** [willmendesneto/ngx-skeleton-loader#4]
**I'm submitting a ...** (check one with "x")

```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
```

**Current behavior**

**Expected behavior**

**Reproduction of the problem**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

- **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX |
  Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

  

- **Language:** [all | TypeScript X.X | ES6/7 | ES5]

- **Node (if applicable):** `node --version` =

**Comment by willmendesneto** [comment]
Hi @raihan71 . Thanks for open this issue. 

You can easily change the theming using the `[theme]` attribute. As an example, please check this [Stackblitz demo](https://stackblitz.com/edit/ngx-skeleton-loader-sample?file=app%2Fapp.component.html)

**Comment by willmendesneto** [comment]
Closing this issue since the support is available. Thanks @raihan71 , feel free to reopen the issue if needed.
