### ISSUE TITLE
Type errors: count and appearence

### ISSUE THREAD

**Issue by YazaWainakh** [willmendesneto/ngx-skeleton-loader#47]
**I'm submitting a 

- [x] bug report 
- [ ] feature request

**Current behavior**

I am using ngx-skeleton-loader for the first time. installed it and using the example in the documentation but I am getting these errors and not sure why.
![ngx-error1](https://user-images.githubusercontent.com/11799213/98965010-d09fd080-2509-11eb-895e-6cbf273315f3.png)
![ngx-error2](https://user-images.githubusercontent.com/11799213/98965019-d3022a80-2509-11eb-80e8-591d44c7636d.png)

**Expected behavior**

Compile without errors.

**Reproduction of the problem**
```
<div>
  <ngx-skeleton-loader count="1" appearance="line"  [theme]="{
    height: '30px'
  }"></ngx-skeleton-loader>
</div>
```

**Please tell us about your environment:**
OS: Fedora 31
IDE: Visual studio code 

- **Language:** [ TypeScript 3.9.6 | ES6 ]
  "ngx-skeleton-loader": "^2.5.0",
- **Node (if applicable):** `node --version` = v12.18.3

**Comment by willmendesneto** [comment]
Hi @YazaWainakh , thanks for open this issue. I just checked your screenshot and looks like you're using `appearance="line"`which doesn't exist. `line` is the default value, so if you're not passing anything it will render a line. It looks like typescript is complaining about that.

Could you check that and confirm if this is still an issue for you, please?

**Comment by YazaWainakh** [comment]
@willmendesneto thank you for replying. I removed `appearance="line"` and it stopped complaining about it. However, it still complains about `count="5"`

**Comment by willmendesneto** [comment]
@YazaWainakh It looks that's something related to the Lint configuration in your app. I just created a new project using Angular CLI and try to simulate that without issues so far. You can find more details in https://github.com/willmendesneto/testing-ngx-skeleton-loader/commit/231f5f3e826e1df79e89d5f954147bcff2a66819

<img width="919" alt="Screen Shot 2020-11-15 at 4 53 42 pm" src="https://user-images.githubusercontent.com/1252570/99178010-1f947280-2763-11eb-88aa-a59b27cb67d7.png">

Could you check that, please?

**Comment by YazaWainakh** [comment]
I tried `ng lint` and all files passed linting.

**Comment by willmendesneto** [comment]
👍 Thanks for sharing @YazaWainakh . Closing this issue for now

**Comment by YazaWainakh** [comment]
`ng lint` is working but the `count` error is still there unfortunately :S

**Comment by willmendesneto** [comment]
@YazaWainakh so it means that's something specific in your build step since `ng lint` should get this issue as well.

**Comment by YazaWainakh** [comment]
I see .. ok I will check and if I find the problem I will post it here for others in case anyone else runs into it. Thanks.

**Comment by YazaWainakh** [comment]
The issue seems to be in the syntax, when count is written as ` [count]="1"` with square brackets, the error is fixed.
```
<div>
  <ngx-skeleton-loader [count]="1" [theme]="{ height: '30px'}"></ngx-skeleton-loader>
</div>

```
