### ISSUE TITLE
SVG Template

### ISSUE THREAD

**Issue by GlauberF** [willmendesneto/ngx-skeleton-loader#6]
The library is very good, but I miss being able to create some template based on an SVG, example as discussed here in this library.

https://angularscript.com/skeleton-loader-for-angular-ngx-skltn/

**Comment by willmendesneto** [comment]
Hi @GlauberF thanks for raise that.

Actually, this package is designed to not use svg to make more flexible for the consumers to handle the skeletons, theming, and also animations.

That was a conscious decision. I’ve tried that in the past and as the package had a huge bundle increase. If you check the Stackblitz examples the FPS of the skeleton has a good performance and the bundle of this package is >1kB.

**Comment by willmendesneto** [comment]
Closing this issue for now. Please feel free to reopen if required.
