### ISSUE TITLE
Table Skeleton

### ISSUE THREAD

**Issue by floriansiepe** [willmendesneto/ngx-skeleton-loader#63]
# Feature Request

Loading skeleton for tables based on Material guidelines.

![Example](https://i.stack.imgur.com/PAXAk.png)

Using a line indicator for tables does not fulfill a proper loading skeleton for a table since the shapes are fundamentally different.

Amount of columns and line should be configurable.

**Comment by willmendesneto** [comment]
hi @floriansiepe . Thanks for raising this issue.

Could you please create an example of the request you're mentioning in https://stackblitz.com/edit/ngx-skeleton-loader-sample and share in this issue, please? Thanks!

**Comment by willmendesneto** [comment]
Hi @floriansiepe .

I just checked the described scenario and the component is working as expected. You can find a scenario simulation in this link https://stackblitz.com/edit/angular-material-table-ngx-skeleton-loader?file=app/app.component.html

So, I'm closing this ticket for now, thanks for raising this issue!
