### ISSUE TITLE
 theme, quotes

### ISSUE THREAD

**Issue by GlauberF** [willmendesneto/ngx-skeleton-loader#7]
Some property, when not using quotation marks, does not work.
I believe the ideal would be to quote with quotes and without quotes too

![Captura de Tela_selecionar área_20190724155235](https://user-images.githubusercontent.com/11314585/61820290-14f5f180-ae2b-11e9-9412-79b9346a79d4.png)

**Comment by willmendesneto** [comment]
Hi @GlauberF thanks for raise that.

This is a concern of the final consumer. This is based on the tooling for code styling used for the developer, so we can’t cover that easily without increase the bundle size significantly and/or impact in performance of this package.

**Comment by willmendesneto** [comment]
Closing this issue for now. Please feel free to reopen if required.
