### ISSUE TITLE
Angular 12.0.3 - NgxSkeletonLoaderComponent` need to receive 'appearance' as: circle or empty string. Forcing default to "''"

### ISSUE THREAD

**Issue by BruneXX** [willmendesneto/ngx-skeleton-loader#79]
**I'm submitting a ...
- [x ] bug report => since angular update to v12

**Current behavior**

Following error appears using angular v12:
`
NgxSkeletonLoaderComponent need to receive 'appearance' as: circle or empty string. Forcing default to "''"
`

**Expected behavior**
No errors using the library with latest angular verison

**Reproduction of the problem**
Just install Angular 12 and ngx-skeleton-loader

**What is the motivation / use case for changing the behavior?**
Update the library to be compatible with Angular v12

**Please tell us about your environment:**

- Debian Linux
- Chrome latest (90.x)
- Angular 12.0.3
- Node 14.17.0
- Npm 7.16.0
- Language: TypeScript 4.x

**Comment by willmendesneto** [comment]
Hi @BruneXX .

As mentioned in this pull request https://github.com/willmendesneto/ngx-skeleton-loader/pull/80#issuecomment-856041981, this is not a blocker for Angular v12. The issue you're facing is related to a misconfiguration (there's no `line` appearance on the module at the moment) and Angular v12 has some strict rules that got your app affected by that.

So I'm closing this issue at the moment. Thanks for raising that and for supporting this project <3
