### ISSUE TITLE
Nothing prevents calling forRoot several times

### ISSUE THREAD

**Issue by HunteRoi** [willmendesneto/ngx-skeleton-loader#81]
**I'm submitting a ...**

- [x] bug report => search github for a similar issue or PR before submitting
- [ ] feature request

**Current behavior**
When you build your application, if you misconfigure the application by calling `NgxSkeletonLoaderModule.forRoot()` at several places, nothing is returned to the developer saying they should avoid it.

**Expected behavior**
An error in dev mode to tell the developer not to configure the module several times in their application.

**Reproduction of the problem**
1) create a project
2) `npm i ngx-skeleton-loader`
3) create a submodule and add `NgxSkeletonLoaderModule.forRoot()` to its `imports` array
4) do the same with the application's main module (AppModule)

**What is the motivation / use case for changing the behavior?**
https://github.com/willmendesneto/ngx-skeleton-loader/pull/77#discussion_r649085709
https://github.com/willmendesneto/ngx-skeleton-loader/pull/77#discussion_r649134309

**Comment by HunteRoi** [comment]
Hey there, @willmendesneto ! I hope you are doing great.

Do you plan to make a move to solve this issue without any breaking change in the current behavior of the library?

Cheers! :beers:

**Comment by willmendesneto** [comment]
Hey @HunteRoi . No plans at the moment, unfortunately. I'm kinda busy these days and I won't be able to work directly on this issue, but I'm happy to support and review any code changes if you're keen to raise a pull request.

**Comment by willmendesneto** [comment]
@HunteRoi Sharing some updates on this one:

Unfortunately, the idea of having it without breaking changes won't be possible, indeed. This is because the module loads more than once even if added & loaded in a shared module async. So, the safest way to make sure consumers won't face this issue in production is by throwing an error.

I'm working on it and a new version will be published soon

**Comment by willmendesneto** [comment]
Some good news: the issue was solved and I just published a new version of `ngx-skeleton-loader` with that. Please update your project to use `ngx-skeleton-loader@3.0.0` to use the latest changes in your project 🚀

Closing this issue. Thanks @HunteRoi for raising that!
