### ISSUE TITLE
Ensures every ARIA progressbar node has an accessible name

### ISSUE THREAD

**Issue by rkristelijn** [willmendesneto/ngx-skeleton-loader#82]
**I'm submitting a ...** (check one with "x")

- [x] bug report => search github for a similar issue or PR before submitting

**Current behavior**

When running axe-core on the demo application of this repository, you will get the following errors:

Impact: serious
Issue Tags: cat.aria, wcag2a, wcag111
Issue Description: Ensures every ARIA progressbar node has an accessible name
Axe-core: 4.2.3

This is caused by missing `aria-label` on the `<span>` element.

**Expected behavior**

When running ngx skeleton loader I would expect no accessibility issues.

**Reproduction of the problem**

clone the repo, `npm i`, `npm start`, run the axe-core plugin.

![image](https://user-images.githubusercontent.com/21142148/125284682-0f488d80-e31a-11eb-90c5-1d17f5a9f9ee.png)

**What is the motivation / use case for changing the behavior?**

Accessibility doesn't need a business case. An inaccessible app is a broken app.

**Please tell us about your environment:**

- **Browser:** [all ]
- **Language:** [all]

**Comment by rkristelijn** [comment]
fixed in #83

**Comment by willmendesneto** [comment]
Thanks @rkristelijn for the issue and the pull request ! Sharing some updated about this issue

The pull request got merged and all the validations pre publish are done. Please update your project to use `ngx-skeleton-loader@2.10.1` to get this issue fixed and enjoy!

Closing this issue for now. Once again, thanks @rkristelijn !
