### ISSUE TITLE
Ivy Distribution Error

### ISSUE THREAD

**Issue by jdgamble555** [willmendesneto/ngx-skeleton-loader#92]
When I upgraded to Angular 13, I am getting this message:

```typescript
Generating browser application bundles (phase: setup)...Processing legacy "View Engine" libraries:
- ngx-skeleton-loader [es2015/esm2015] (git+https://github.com/willmendesneto/ngx-skeleton-loader.git)
Encourage the library authors to publish an Ivy distribution.
```

J

**Comment by willmendesneto** [comment]
Hi @jdgamble555 ! Thanks for raising this issue!

This is something I'm looking at the moment, just need more time to apply the migration and a new version for the project will be published as a major version to keep parity with angular projects using any previous version for the Framework itself..


I'll share the updates here as soon as I get them in place!

**Comment by arsen-melkumiants** [comment]
Hi guys, should we expect the fix to be deployed in near future? 
I see PR is failing due to a declaration issue since 2021-12-18

**Comment by arsen-melkumiants** [comment]
@willmendesneto Oh, that sucks....I hope you are feeling better now 🤞

And thank you for the quick response!

**Comment by jdgamble555** [comment]
Just a small reminder on this :0

**Comment by willmendesneto** [comment]
Hi folks, sharing some great news:

The pull request was merged and a new version of `ngx-skeleton-loader` was published! Also, all the demos/examples are updated with the latest version of the module and Angular Dependencies 🎉🎉🎉

Please feel free to update your project with the latest version of this module - AKA `ngx-skeleton-loader@5.0.0` and enjoy!

Thanks folks 👋
