### ISSUE TITLE
Component theme should not replace forRoot theme

### ISSUE THREAD

**Issue by tek-moglykisvergad** [willmendesneto/ngx-skeleton-loader#94]
**I'm submitting a ...** (check one with "x")

- [ ] bug report => search github for a similar issue or PR before submitting
- [x] feature request

**Current behavior**

If a theme is specified in `forRoot`, it will be completely overridden by a component's theme.

For example:

Module:

  ```
  imports: [
    ...
    NgxSkeletonLoaderModule.forRoot({ theme: { 'background-color': '#ff0000', opacity: '0.9' } }),
    ...
  ],
```

Component's html:
```
  <ngx-skeleton-loader
    [theme]="{ 
      'border-radius': '5px',
      height: '50px',
      opacity: '0.5'
      border: '1px solid white'
    }"
  ></ngx-skeleton-loader>
```

In this case, `background-color` would be removed, despite the component's theme not containing a value for it.

**Expected behavior**

The theme defined in `forRoot` should not be replaced completely by the component's theme.

In the example above, I would expect `opacity` to be overridden, but `background-color` to be preserved.

**Reproduction of the problem**

**What is the motivation / use case for changing the behavior?**

This would be valuable in cases where we want to define properties that should be applied for each component, while also allowing a component to specify its own properties.

**Please tell us about your environment:**

- **Browser:** all

  

- **Language:** all

- **Node (if applicable):** `node --version` = 16.13.0

**Comment by willmendesneto** [comment]
Hi @tek-moglykisve
Thsanks for raising this issue! I'm about to publish a new version of `ngx-skeleton-loader` with this new feature. I'll share more details in here as soon as I finish with that task, but thanks heaps for the suggestion!

**Comment by willmendesneto** [comment]
Hi @tek-moglykisvergad , how are you?

AT TIME:

Pull request is now merged and the feature is in place! You can find more details about that on the README's section  "[Extending theme via NgxSkeletonLoaderModule.forRoot()](https://github.com/willmendesneto/ngx-skeleton-loader#extending-theme-via-ngxskeletonloadermoduleforroot)"

---

> By default when using `NgxSkeletonLoaderModule.forRoot({ theme: /* ...list of CSS atributes */} })` the application is using this value as source of truth, overriding any local theming passed to `<ngx-skeleton-loader>` component via `[theme]` input. Check these steps in case you need to change this behaviour in your app

This method is also accepting the option of having a global theme and local theme inputs. You can enable it by passing `NgxSkeletonLoaderModule.forRoot({ theme: { extendsFromRoot: true, /* ...list of CSS atributes */} })` in your module. Quite simple, right? 😄

By using that configuration in yuor application, you should also be aware that:

- By default, every `<ngx-skeleton-loader>` component will use `theme` coming from `NgxSkeletonLoaderModule.forRoot()` as the source of truth
- If there's any CSS attribute on the component locally which overrides the CSS spec, it combines both themes, but overriding global CSS attributes in favor of local ones.

As an example:

```typescript
...
import { NgxSkeletonLoaderModule } from 'ngx-skeleton-loader';
...

@NgModule({
  declarations: [
    YourAppComponent
  ],
  imports: [
    ...
    NgxSkeletonLoaderModule.forRoot({
      theme: {
        // Enabliong theme combination
        extendsFromRoot: true,
        // ... list of CSS theme attributes
        height: '30px',
      },
    }),,
    ...
  ],
  providers: [],
  bootstrap: [YourAppComponent]
})

export class YourAppComponent {}

```

```html
<div class="item">
  <ngx-skeleton-loader></ngx-skeleton-loader>
  <!-- above line will produce a skeleton component using `height: 30px;`" -->
  <ngx-skeleton-loader [theme]="{background: 'blue'}"></ngx-skeleton-loader>
  <!-- above line will produce a skeleton component using `height: 30px; background: blue;`" -->
  <ngx-skeleton-loader [theme]="{height: '50px', background: 'red'}"></ngx-skeleton-loader>
  <!-- above line will produce a skeleton component using `height: 50px; background: red;`" -->
</div>
```

**Comment by willmendesneto** [comment]
Sharing some great news @tek-moglykisvergad ! 

this feature is now available on the latest version of `ngx-skeleton-loader`. Please upgrade your project to use `ngx-skeleton-loader@7/0.0` and enjoy!

Closing this issue since it's solved. Thank you very much! 🎉
