### ISSUE TITLE
v13 support

### ISSUE THREAD

**Issue by soori-reddy** [willmendesneto/ngx-skeleton-loader#95]
**I'm submitting a ...** (check one with "x")

- [ ] bug report => search github for a similar issue or PR before submitting
- [ ] feature request

**Current behavior**

**Expected behavior**

**Reproduction of the problem**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

- **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX |
  Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

  

- **Language:** [all | TypeScript X.X | ES6/7 | ES5]

- **Node (if applicable):** `node --version` =

**Comment by willmendesneto** [comment]
Hi @soori-reddy. This is issue is duplicated of #92 , so I'm sharing the same news here as well!

> Hi folks, sharing some great news:
> 
> The pull request was merged and a new version of `ngx-skeleton-loader` was published! Also, all the demos/examples are updated with the latest version of the module and Angular Dependencies 🎉🎉🎉
> 
> Please feel free to update your project with the latest version of this module - AKA `ngx-skeleton-loader@5.0.0` and enjoy!
> 
> Thanks folks 👋

Saying that, I'm closing this issue. Thanks a lot for raising that!
